# Generated by Django 5.0.6 on 2024-06-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlitem',
            name='key',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='urlitem',
            name='long_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='urlitem',
            name='short_url',
            field=models.URLField(default=''),
        ),
    ]
